### ISSUE TITLE
DefaultAggregatorBuildContext is not correct when output changes

### ISSUE THREAD

**Issue by virtuald** [takari/io.takari.incrementalbuild#16]
Adding the following to the `testBasic` unit test shows this failure:

    // output changed for some reason
    Files.write(new byte[] {0x01}, outputFile);
    indexer = new FileIndexer();
    actx = newContext();
    output = actx.newInputSet();
    output.addInputs(basedir, null, null);
    output.aggregateIfNecessary(outputFile, indexer);
    actx.commit(null);
    Assert.assertTrue(outputFile.canRead());
    Assert.assertEquals(1, indexer.outputs.size());

I haven't looked, but I suspect this is also true for the other incremental build pieces?

Now, I think one could have a good philosophical debate about whether this is expected behavior or not -- if the user changes the output out from underneath the build process without telling it, you could argue that the user deserves what they get. But what if something else changes it without the user knowing? Perhaps git changed the endlines if it's a text file, or some malware (though, you have other issues in that case), or perhaps the build process was generating python files and the user inserted some debugging stuff into the output file (I've done this!). In all of these cases I would expect that a rebuild would replace the output file.

**Comment by ifedorenko** [comment]
Earlier versions of incremantalbuild library used to rebuild modified outputs, but we removed that behaviour. Philosophy aside, there were good practical reasons for the change.

First, tracking reverse, i.e. output-to-input association has significant overhead, both in terms of performance and overall implementation/behaviour of the library. Reasoning about chained generations like input->generated-input->output (think java annotation processing, for example), becomes much more complicated. In-place class file manipulation by tools like aspectj and proguard is another example when incremental rebuild of changed outputs is either not possible at all or at least very tricky to implement properly.

Second, but not as critical, I often use the same source tree both for command line builds and for eclipse work (I think many do). It was really annoying to see command line recompile all/most sources just because the same sources were compiled inside eclipse.

Also anecdotally, nobody appears to complain about current behaviour. 

If you feel really strongly about rebuilding modified outputs, the easiest way to implement this is to "escalate" build if any of the old outputs changed. I suggest you try this and if you like the result we can discuss how to integrate it back to the library.

**Comment by virtuald** [comment]
Ok, those practical reasons seem fine to me, it was just a bit unexpected when I ran into it. It would be good to add a note to document it.
